### ISSUE TITLE
Example of Get and Post

### ISSUE THREAD

**Issue by 1Map** [hgarcia/curling#3]
Hi,
Can I please have 2 examples of a Get and a Post as I am having difficulty using curling.

I do:
```
var curl = require('curling')
var connection = curl.connect(null)
connection.get('whateverurl', {}, (err, result) => {
    // After call
})
```

But it says that **ctx.run is not a function**

**Comment by 1Map** [comment]
Don't worry, I got it working by changing the code to:

```
var curl = require('curling')
curl.run = require('curling/lib/curl-transport').run
var connection = curl.connect(null)
connection.get('whateverurl', {}, (err, result) => {
    // After call
})
```

**Comment by 1Map** [comment]
Apparantly you only have:

`exports.connect = require("./lib/curl-transport").connect;`

and not:

```
exports.connect = require("./lib/curl-transport").connect;
exports.run = require("./lib/curl-transport").run;
```

in your **index.js** file

**Comment by hgarcia** [comment]
That was removed in version 1.0.0 due to a reported vulnerability and re-added in version 1.1.0 thanks to a pull request by @snoopysecurity. Sorry about that.
